/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandbookIndexRouteImport } from './routes/handbook.index'
import { Route as HandbookTopicIdRouteImport } from './routes/handbook.$topicId'

const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookIndexRoute = HandbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HandbookRoute,
} as any)
const HandbookTopicIdRoute = HandbookTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => HandbookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handbook': typeof HandbookRouteWithChildren
  '/handbook/$topicId': typeof HandbookTopicIdRoute
  '/handbook/': typeof HandbookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handbook/$topicId': typeof HandbookTopicIdRoute
  '/handbook': typeof HandbookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/handbook': typeof HandbookRouteWithChildren
  '/handbook/$topicId': typeof HandbookTopicIdRoute
  '/handbook/': typeof HandbookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/handbook' | '/handbook/$topicId' | '/handbook/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/handbook/$topicId' | '/handbook'
  id: '__root__' | '/' | '/handbook' | '/handbook/$topicId' | '/handbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandbookRoute: typeof HandbookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook/': {
      id: '/handbook/'
      path: '/'
      fullPath: '/handbook/'
      preLoaderRoute: typeof HandbookIndexRouteImport
      parentRoute: typeof HandbookRoute
    }
    '/handbook/$topicId': {
      id: '/handbook/$topicId'
      path: '/$topicId'
      fullPath: '/handbook/$topicId'
      preLoaderRoute: typeof HandbookTopicIdRouteImport
      parentRoute: typeof HandbookRoute
    }
  }
}

interface HandbookRouteChildren {
  HandbookTopicIdRoute: typeof HandbookTopicIdRoute
  HandbookIndexRoute: typeof HandbookIndexRoute
}

const HandbookRouteChildren: HandbookRouteChildren = {
  HandbookTopicIdRoute: HandbookTopicIdRoute,
  HandbookIndexRoute: HandbookIndexRoute,
}

const HandbookRouteWithChildren = HandbookRoute._addFileChildren(
  HandbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandbookRoute: HandbookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
